"use client";
import { useState } from "react";
import Link from "next/link";

const steps = ["Personal", "College", "Identity", "Events", "Emergency", "Review"];
type FormState = { fullName:string; email:string; phone:string; collegeId:string; collegeRollNumber:string; emergencyName:string; emergencyPhone:string; eventIds:string[] };

export default function RegisterPage() {
  const [step,setStep]=useState(0); const [submitted,setSubmitted]=useState(false); const [message,setMessage]=useState(""); const [photo,setPhoto]=useState<File|null>(null); const [collegeIdFile,setCollegeIdFile]=useState<File|null>(null);
  const [form,setForm]=useState<FormState>({fullName:"",email:"",phone:"",collegeId:"",collegeRollNumber:"",emergencyName:"",emergencyPhone:"",eventIds:[]});
  const update=(key:keyof FormState,value:string)=>setForm(old=>({...old,[key]:value}));
  async function submit(){setMessage("");const response=await fetch("/api/participants",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const body=await response.json() as {message?:string;participantId?:string};if(!response.ok||!body.participantId){setMessage(body.message??"Registration could not be submitted.");return;}for(const [file,bucket] of [[photo,"participant-photos"],[collegeIdFile,"college-ids"]] as const){if(file){const upload=new FormData();upload.append("participantId",body.participantId);upload.append("bucket",bucket);upload.append("file",file);const uploadResponse=await fetch("/api/uploads",{method:"POST",body:upload});if(!uploadResponse.ok){setMessage("Registration saved, but a document upload failed. Please retry from your dashboard.");return;}}}setSubmitted(true);}
  if(submitted)return <main className="section" style={{maxWidth:720}}><div className="eyebrow">Registration received</div><h1 className="display" style={{fontSize:"clamp(3rem,7vw,6rem)"}}>You’re<br/><span style={{color:"var(--violet)"}}>in the system.</span></h1><p className="muted" style={{lineHeight:1.6}}>Your application is pending verification. Once approved, your ILLENIUM ID and QR pass will be generated automatically.</p><Link href="/login" className="btn btn-primary">Go to login</Link></main>;
  return <main className="section" style={{maxWidth:900}}><div className="eyebrow">Participant registration</div><h1 className="display" style={{fontSize:"clamp(3rem,7vw,6rem)",marginBottom:"2rem"}}>Claim your<br/><span style={{color:"var(--violet)"}}>place here.</span></h1><div className="panel" style={{background:"rgba(255,255,255,.04)",borderColor:"var(--line)",color:"white"}}><div style={{display:"flex",gap:".45rem",flexWrap:"wrap",marginBottom:"2rem"}}>{steps.map((label,index)=><span key={label} className="tag" style={{opacity:index===step?1:.45}}>{String(index+1).padStart(2,"0")} · {label}</span>)}</div>
    {step===0&&<div className="form-grid"><label className="field"><span>Full name</span><input className="input" value={form.fullName} onChange={e=>update("fullName",e.target.value)}/></label><label className="field"><span>Email</span><input className="input" type="email" value={form.email} onChange={e=>update("email",e.target.value)}/></label><label className="field"><span>Phone</span><input className="input" value={form.phone} onChange={e=>update("phone",e.target.value)}/></label></div>}
    {step===1&&<div className="form-grid"><label className="field full"><span>College ID (UUID from festival admin)</span><input className="input" value={form.collegeId} onChange={e=>update("collegeId",e.target.value)} placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"/></label><label className="field"><span>College roll number</span><input className="input" value={form.collegeRollNumber} onChange={e=>update("collegeRollNumber",e.target.value)}/></label></div>}
    {step===2&&<div className="form-grid"><p className="muted full">Private documents are stored in Supabase Storage and never encoded into the QR.</p><label className="field"><span>Participant photo</span><input className="input" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]??null)}/></label><label className="field"><span>College ID</span><input className="input" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setCollegeIdFile(e.target.files?.[0]??null)}/></label><label className="field full"><span><input type="checkbox" required/> I confirm the information belongs to me.</span></label></div>}
    {step===3&&<div><p className="muted">Event selection is saved with your registration.</p><label className="field"><span>Event IDs (comma-separated UUIDs, optional)</span><input className="input" value={form.eventIds.join(",")} onChange={e=>setForm(old=>({...old,eventIds:e.target.value.split(",").map(v=>v.trim()).filter(Boolean)}))}/></label></div>}
    {step===4&&<div className="form-grid"><label className="field"><span>Emergency contact name</span><input className="input" value={form.emergencyName} onChange={e=>update("emergencyName",e.target.value)}/></label><label className="field"><span>Emergency contact phone</span><input className="input" value={form.emergencyPhone} onChange={e=>update("emergencyPhone",e.target.value)}/></label></div>}
    {step===5&&<pre style={{whiteSpace:"pre-wrap",color:"#c9c7d6",lineHeight:1.8}}>{JSON.stringify(form,null,2)}{"\n\n"}By submitting, you agree that festival staff may verify your college identity for event access.</pre>}
    {message&&<p style={{color:"#ff9aa5"}}>{message}</p>}<div style={{display:"flex",justifyContent:"space-between",marginTop:"2rem"}}>{step>0?<button className="btn btn-ghost" onClick={()=>setStep(step-1)}>Back</button>:<span/>}{step<steps.length-1?<button className="btn btn-primary" onClick={()=>setStep(step+1)}>Continue</button>:<button className="btn btn-primary" onClick={submit}>Submit registration</button>}</div></div></main>;
}
