"use client";
import { useEffect, useRef, useState } from "react"; import Link from "next/link"; import { BrowserMultiFormatReader } from "@zxing/browser";
type Result = { status: string; message?: string; participant?: { full_name: string; illenium_id: string; college: string }; checkedInAt?: string };
export default function ScannerPage(){ const videoRef=useRef<HTMLVideoElement>(null); const readerRef=useRef<BrowserMultiFormatReader|null>(null); const [mode,setMode]=useState<"event_entry"|"campus_entry">("event_entry"); const [manual,setManual]=useState(""); const [activeToken,setActiveToken]=useState(""); const [result,setResult]=useState<Result|null>(null); const [error,setError]=useState(""); const [scanning,setScanning]=useState(false); const eventId="";
  async function verify(token:string){setActiveToken(token);setScanning(false);const response=await fetch("/api/verification",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,eventId:eventId||undefined})});setResult(await response.json() as Result);}
  async function start(){setError("");setResult(null);try{const reader=new BrowserMultiFormatReader();readerRef.current=reader;setScanning(true);await reader.decodeFromConstraints({video:{facingMode:{ideal:"environment"}}},videoRef.current!,async (decoded)=>{if(decoded){await verify(decoded.getText());}});}catch{setScanning(false);setError("Camera access is blocked or unavailable. Allow camera access in browser settings or use manual ILLENIUM ID entry.");}}
  useEffect(()=>()=>{const stream=videoRef.current?.srcObject as MediaStream|null;stream?.getTracks().forEach(track=>track.stop());},[]);
  async function checkIn(){if(!result?.participant)return;const response=await fetch("/api/check-ins",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token:activeToken||manual,checkInType:mode,eventId:eventId||undefined})});const body=await response.json() as {message?:string;ok?:boolean};setResult({...result,status:body.ok?"checked_in":"invalid",message:body.message??(body.ok?"Check-in saved.":"Check-in failed.")});}
  return <div className="app-shell" style={{background:"#080810",color:"white"}}><header className="app-nav"><Link href="/oc/dashboard" className="brand"><span className="brand-mark"><span>✦</span></span> ILLENIUM 2026</Link><span>SCANNER</span></header><main className="scanner-shell"><div className="scanner-stage"><div style={{display:"flex",gap:".5rem",marginBottom:"1rem"}}><button className={`btn ${mode==="event_entry"?"btn-primary":"btn-ghost"}`} onClick={()=>setMode("event_entry")}>Event entry</button><button className={`btn ${mode==="campus_entry"?"btn-primary":"btn-ghost"}`} onClick={()=>setMode("campus_entry")}>Campus entry</button></div><div className="camera-frame"><video ref={videoRef} muted playsInline/><div className="scan-crosshair"/><div style={{position:"absolute",bottom:"1rem",width:"100%",textAlign:"center",fontSize:".85rem"}}>Align the QR inside the frame</div></div>{error&&<div className="result-card result-invalid">{error}</div>}<div style={{display:"flex",gap:".6rem",marginTop:"1rem"}}><button className="btn btn-primary" style={{flex:1}} onClick={start}>{scanning?"Scanning…":"Start camera"}</button><button className="btn btn-ghost" onClick={()=>{setScanning(false);const stream=videoRef.current?.srcObject as MediaStream|null;stream?.getTracks().forEach(track=>track.stop());}}>Stop</button></div><div className="result-card"><label className="field" style={{color:"white"}}>Enter ILLENIUM ID manually<input className="input" value={manual} onChange={e=>setManual(e.target.value)} placeholder="ILL-26-000123" /></label><button className="btn btn-ghost" style={{width:"100%",marginTop:".7rem"}} onClick={()=>verify(manual)}>Verify ID</button></div>{result&&<div className={`result-card ${result.status==="valid"||result.status==="checked_in"?"result-valid":"result-invalid"}`}><h2>{result.status==="valid"?"✓ VALID PARTICIPANT":result.status==="already_checked_in"?"⚠ ALREADY CHECKED IN":result.status==="checked_in"?"✓ CHECKED IN":"! "+result.status.toUpperCase()}</h2>{result.participant&&<><p><strong>{result.participant.full_name}</strong><br/>{result.participant.illenium_id} · {result.participant.college}</p>{result.status==="valid"&&<button className="btn btn-primary" style={{width:"100%"}} onClick={checkIn}>Check in participant</button>}</>}{result.message&&<p className="muted">{result.message}</p>}</div>}</div></main></div>;
}
